puridiom.controller('ResourcesController', function($scope) {
	$scope.whitepapers = [
		{image: 'backend_resources/images/resources/whitepaper/5-cost-reduce-edu.jpg', link: 'http://info.puridiom.com/cost-control-education', title: '5 Cost Reduction Opportunities for Education', description:'With costs rising in the education industry, saving opportunities are increasingly important; this whitepaper goes over five major options when considering ways to cut down on spending.'},
		{image: 'backend_resources/images/resources/whitepaper/cost-control-edu.jpg', link: 'http://info.puridiom.com/cost-control-education-wp', title: 'Cost Control for Education', description:'This whitepaper will help readers shape sustainable cost control for Catholic and private schools.'},
		{image: 'backend_resources/images/resources/whitepaper/Puridiom-5-pain-points.jpg', link: 'http://info.puridiom.com/5-ways-improve-procurement', title: '5 Ways to Improve Your Procurement Process', description:'Whether you are an organization that does its procurement manually, or you are partially or fully automated, there are always those pain points that could be improved upon. We have pinpointed the areas that are most often a problem for companies and have listed a few suggestions on how to improve procurement in these areas.'},
		{image: 'backend_resources/images/resources/whitepaper/cloud.jpg', link: 'http://info.puridiom.com/cloud-vs-licensed', title: 'Learn Four Crucial Factors when Considering Cloud vs Licensed', description:'Your company has determined it needs an automated purchasing system. Research begins and two words keep popping up... Cloud or Licensed. This white paper will explain the the terms and help you choose the right eProcurement platform for your organization. The information could send you down the path to dramatic savings!'},
		{image: 'backend_resources/images/resources/whitepaper/user-adoption.jpg', link: 'http://info.puridiom.com/user-adoption', title: 'Learn the Steps to Successful User Adoption', description:"An eProcurement solution is as successful as its deployment.By taking the first steps of eProcurement user adoption organizations can take off running and enjoy the benefits of today's eProcurement and Spend Management technology. Download this white paper to discover the right steps to improve your user adoption."},
		{image: 'backend_resources/images/resources/whitepaper/Puridiom-5-pain-points-results.jpg', link: 'http://info.puridiom.com/5-ways-prevent-procurement-pinch', title: '5 Ways to Prevent the Procurement Pinch', description:'Where do you feel the pinch in your procurement process? We recently posed this question at the 97th Annual Institute for Supply Management Conference and Educational Exhibit at our exhibit booth. Admittedly, a very unscientific study, but it did yield some pretty consistent results. We received a mixture of answers and summarized the responses.'},
		{image: 'backend_resources/images/resources/whitepaper/Puridiom-Case-for-eProcurement.jpg', link: 'http://info.puridiom.com/case-for-eprocurement', title: 'Learn How to Define Savings with e-Procurement', description:'We answer the top 8 questions about e-Procurement and show you how Puridiom can define your organizations savings. Learn why it is more important than ever to find ways to drive savings to the bottom-line and increase process efficiencies across the entire organization.'},
		{image: 'backend_resources/images/resources/whitepaper/Puridiom-Travel-Management-WP.jpg', link: 'http://info.puridiom.com/travel-management-paper', title: 'The New Approach to Travel Management: Travel Better. Spend Less.', description:'Using the new approach to travel management, all travel, regardless of how it is booked, on-line or through a travel agent, goes through the procurement process, tracking and accounting for every transaction.'},
		{image: 'backend_resources/images/resources/whitepaper/Puridiom_CCM.jpg', link: 'http://info.puridiom.com/catalog-management', title: 'New Catalog Management Technology', description:"Electronic connection to suppliers is critical to achieving cost-effectiveness and efficiency. However, if you struggle to manage supplier catalogs because of multiple data formats, languages, or currencies, a new class of technology may be the solution you are looking for. See how Puridiom's Catalog Content Manager can transform your organization."},
		{image: 'backend_resources/images/resources/whitepaper/Puridiom_Procurement_Strategies.jpg', link: 'http://info.puridiom.com/procurement-strategies', title: '5 Pro-Active Procurement Strategies to Leverage Profitability', description:'Procurement managers have had to look for answers to some of the toughest challenges businesses have ever faced: doing more with fewer resources, dealing with maintaining or finding new suppliers, and countless other issues. However, we believe there are still opportunities to leverage profitability.'},
		{image: 'backend_resources/images/resources/whitepaper/Puridiom-Controlling-Health-Plan-Costs-with-eProcurement.jpg', link: 'http://info.puridiom.com/controlling-health-plans', title: 'Learn How to Control Health Plan Costs with eProcurement', description:'Learn how Puridiom eProcurement can help you company control health plan costs.'},
	];
	$scope.casestudies = [
		{image: 'backend_resources/images/resources/casestudies/Puridiom-Case-Study-BCBSRI.jpg', link: 'http://info.puridiom.com/blue-cross-blue-shield-rhode-island', title: 'Blue Cross & Blue Shield: P2P Results in Healthy Outcomes', description:'Client Profile: Blue Cross & Blue Shield of Rhode Island (BCBSRI) provides health insurance for over 600,000 members. Founded in 1939, it had premium revenue of $2.5 billion in 2010. Business Challenge: Transform purchasing, vendor management, and accounts payable functions through the implementation of an end-to-end procure-to-pay (P2P) system.'},
		{image: 'backend_resources/images/resources/casestudies/Puridiom-Case-Study-VSE-Gov-Contractor.jpg', link: 'http://info.puridiom.com/vse', title: 'VSE: Tightening Up the Ship', description:'Client Profile: VSE Corporation is a government contractor that provides engineering, logistics support, sustainment, foreign military sales, management sciences, information technology, energy and environment support, and facilities management. Business Challenge: To automate a semi-manual, paper-intensive procurement process.'},
		{image: 'backend_resources/images/resources/casestudies/Puridiom-Case-Study-Boart-Longyear-Drilling-Industry.jpg', link: 'http://info.puridiom.com/boart-longyear', title: "Boart Longyear: It's all about Visibility", description:'Client Profile: Boart Longyear is the largest provider of drilling services and drilling products for the global mining industry, with a substantial presence in drilling for other purposes, including water exploration, environmental and oil sands exploration. Business Challenge: To find and choose an e-procurement solution that would provide spend visibility, control, and the ability to enforce compliance.'},
		{image: 'backend_resources/images/resources/casestudies/Puridiom-Case-Study-of-Health-Insurance-Provider.jpg', link: 'http://info.puridiom.com/health-insurance-case-study', title: 'Insurance: eProcurement for Health Insurance Providers', description:"Client Profile: One of the nation's Top Managed Care Providers, with over 3,000,000 members and 20 offices statewide. Business Challenge: To find and choose an e-procurement application that would provide the most cost-savings for the organization, and provide the flexibility needed to work within the business culture and methodologies of the company."},
		{image: 'backend_resources/images/resources/casestudies/Puridiom-Case-Study-of-Oil-Gas-Co.jpg', link: 'http://info.puridiom.com/oil-company', title: 'Cost Savings: The Procurement "well-oiled" machine', description:'Client Profile: An independent Texas-based oil company, with multiple offices, drilling sites, and oil properties throughout the U.S. and a subsidiary in Canada. Business Challenge: To convert a completely manual procurement process to a smoothly running automated procurement function with as little disruption as possible.'},
	];
	$scope.benchmarks = [
		{image: 'backend_resources/images/resources/benchmarks/paystream-report.jpg', link: 'http://info.puridiom.com/paystream-report-2014', title: 'Unlocking the Keys to Dynamic P2P', description:'The  "2014 eProcurement Market Report," explores the growing market trends in electronic procurement technology, highlighting the current uses, benefits, and movements of the software withhttp://info.puridiom.com/trends-predictions-2014', title: 'Procurement: Trends and Predictions 2014', description:'This paper expands upon the 2014 predictions, focusing on: the growth of big data, market volatility, contingent workflow growth, procurement outsourcing growth, and the rise of mobility.'},
		{image: 'backend_resources/images/resources/benchmarks/proc-to-pay-bestinclass.jpg', link: 'http://info.puridiom.com/best-in-class-blueprint', title: 'Procure-to-Pay: The Best-in-Class Blueprint', description:'Learn how Procure-to-Pay can outline the way for Best-in-Class enterprises to excel.'},
		{image: 'backend_resources/images/resources/benchmarks/cfo-and-cpo.jpg', link: 'http://info.puridiom.com/one-world-two-viewpoints', title: 'Strategies to Improve Finance & Procurement Operations', description:"This research report reveals the evolving relationship of the Chief Finance Officer (CFO) and Chief Procurement Officer (CPO) in today's corporate world and offers recommendations for organizations to build a strong and productive relationship."},
		{image: 'backend_resources/images/resources/benchmarks/eproc-benchmark-08.jpg', link: 'http://info.puridiom.com/superior-performance', title: 'Benchmark: Year-Over-Year Superior Performance', description:'Find out how you can achieve Best-in-Class results. Reduce requisition-to-order cycle cost and time by 49% and 65%, respectively.'},
		{image: 'backend_resources/images/resources/benchmarks/converge-proc-and-ap.jpg', link: 'http://info.puridiom.com/supplier-enablement-converging', title: 'Supplier Enablement: Procurement & Accounts Payable', description:'Discover how converging procurement and accounts payable can increase visibility into spend and result in cost savings.'},
		{image: 'backend_resources/images/resources/benchmarks/ap-transform.jpg', link: 'http://info.puridiom.com/ap-transformation', title: 'Accounts Payable: Better, Faster, Cheaper', description:'Find out how you can achieve Best-in-Class results. Best-in-Class enterprises enjoy 76% to 94% lower invoice processing rates than their peers.'},
		{image: 'backend_resources/images/resources/benchmarks/cfo-view-procure.jpg', link: 'http://info.puridiom.com/cfo-view-procurement', title: "The CFO's View of Procurement: Same Page, Different Language", description:"This study benchmarks the results of over 500 survey responses from CFO's and CPO's and recommends improved communication between finance and procurement and the definition of a ''common language'' between the two groups."},
		{image: 'backend_resources/images/resources/benchmarks/connect-with-suppliers.jpg', link: 'http://info.puridiom.com/supplier-enablement-building', title: 'Supplier Enablement: Lasting Relationships with Suppliers', description:'Learn how Best-in-Class enterprises place more than 70% of their spend under the management of procurement.'},
		{image: 'backend_resources/images/resources/benchmarks/eproc-benchmark-08.jpg', link: 'http://info.puridiom.com/eprocurement', title: 'E-Procurement Benchmark Report', description:'The findings in this report set the standard for e-procurement 2.0 programs.'},
	];
	$scope.datasheets = [
		{image: 'backend_resources/images/resources/datasheets/Puridiom-Corporate-Profile.jpg', link: 'http://info.puridiom.com/corporate-profile', title: 'Corporate Profile', description:'Read how Technical Services Associates Inc. (TSA), a software development company, began to introduce automation of core procurement functions on a personal computer.'},
		{image: 'backend_resources/images/resources/datasheets/Puridiom-Total-Procurement-Solution.jpg', link: 'http://info.puridiom.com/total-procurement', title: 'Total Procurement Solution', description:'Learn how Puridiom automates the procure-to-pay process by empowering and equipping individuals with innovative tools to improve overall performance and compliance.'},
		{image: 'backend_resources/images/resources/datasheets/Puridiom-eSourcing-Solution.jpg', link: 'http://info.puridiom.com/esourcing', title: 'e-Sourcing Solution', description:'Learn how Puridiom enables you to leverage automation and achieve "Best Value Souring" through the introduction of a unique sourcing technology.'},
		{image: 'backend_resources/images/resources/datasheets/Puridiom-Contract-Management-Solution.jpg', link: 'http://info.puridiom.com/contract-management', title: 'Contract Management Solution', description:'Fulfill your need for a comprehensive solution that encompasses all of the facets of contract management.'},
		{image: 'backend_resources/images/resources/datasheets/Puridiom-Catalog-Content-Manager.jpg', link: 'http://info.puridiom.com/catalog-content-manager', title: 'Catalog Content Manager', description:"Read how Puridiom's CCM tool creates a web marketplace that is easily accessible by buyer and supplier to meet daily challenges, such as efficiency and visibility."},
		{image: 'backend_resources/images/resources/datasheets/Puridiom-Travel-Management.jpg', link: 'http://info.puridiom.com/travel-management', title: 'Travel Management', description:"Make travel visible with Puridiom's new approach to travel management, which can send all travel through the procurement process."},
		{image: 'backend_resources/images/resources/datasheets/puridiom-eipp-ds.jpg', link: 'http://info.puridiom.com/eipp', title: 'Electronic Invoice Presentment and Payment', description:'What is EIPP (Electronic Invoice Presentment and Payment) and is it right for your organization? Read more to find out.'},
		{image: 'backend_resources/images/resources/datasheets/Puridiom-eProcurement-for-Health-Plans.jpg', link: 'http://info.puridiom.com/eprocurement-health-plans', title: 'eProcurement for Health Plans', description:'The world of insurance is changing fast. Keep up with Health Care Reform (HCR) requirements that are directly impacting the way insurance companies are managed.'},
		{image: 'backend_resources/images/resources/datasheets/admin-cost-reduce.jpg', link: 'http://info.puridiom.com/administrative-cost-control', title: 'Strategic Services For Administrative Cost Reduction', description:'Performance diagnostics, cost reducing services, and business process outsourcing highlight this crucial datasheet.'},
	];
	$scope.podcasts = [
		{image: 'backend_resources/images/resources/podcasts/evolution_rc.jpg', link: 'http://info.puridiom.com/evolution-procurement', title: 'How the Role of Procurement Affects Your Business', description:"Date: 9/22/2010 Duration: 13:08 The Evolution of Procurement - Discover how Puridiom's product and services have evolved as the role of procurement has become an increasingly integral part of today's organizations."},
		{image: 'backend_resources/images/resources/podcasts/puridiom_atriis.jpg', link: 'http://info.puridiom.com/traveling-procurement', title: 'Managing Travel with Procurement', description:"Date: 8/09/2010 Duration: 13:03 Travel has become the new procurement challenge, where businesses are looking to maximize travel savings for management while accommodating the needs of business travelers. Puridiom and ATRIIS have collaborated to provide a breakthrough solution for this challenge. ETM's Ali Klaver chatted to Puridiom CEO Jesus Ramos and Yaron Perlman, CTO and Vice President of Business Development at ATRIIS, about the partnership."},
		{image: 'backend_resources/images/resources/podcasts/puridiomCEO_rc.jpg', link: 'http://info.puridiom.com/eprocurement-trending', title: "Learn What's Trending in eProcurement", description:"Date: 7/15/2010 Duration: 7:16 Jesus Ramos, President and CEO of Puridiom, joins ETM's Ali Klaver to discuss market trends around procurement solutions, as well as to talk about Puridiom, how the company has become successful, and why our solution works so well."},
	];
	$scope.webcasts = [
		{image: 'backend_resources/images/resources/webcasts/collaborative-procurement-webinar.jpg', link: 'http://post.puridiom.com/acton/media/5671/collaborative-procurement', title: 'Collaborative Procurement', description:'This webinar will discuss the key stakeholders that procurement must engage to meet its business objectives and drive increased enterprise value.'},
		{image: 'backend_resources/images/resources/webcasts/procurement-challenges-webcast.jpg', link: 'http://mail.sdcexec.com/portal/wts/uemcm0qfeO7aefErk6jjmreq%7CPnO-z2kz-Pyg-AfPwOb', title: 'Procurement Challenges for Small to Mid-Size Companies', description:'The role of procurement is evolving. It might be easier for the big guys with established procurement departments to adapt, but what about smaller companies? Can their procurement leaders evolve with the industry? How do they deliver the strategies that are required for business survival? And what does the executive team need to know, and do? '},
		{image: 'backend_resources/images/resources/webcasts/cta_measuring_stick.jpg', link: 'http://post.puridiom.com/acton/fs/blocks/showLandingPage/a/5671/p/p-0062/t/page/fm/1', title: 'Strategies to Measure and Improve Procurement Performance', description:"What is the standard of comparison when it comes to procurement performance? Do you know how to translate procurement savings into metrics that resonate with finance? Are you finding and taking advantage of all the opportunities that can come from a collaborative CPO/CFO partnership? This web seminar will show you how to develop collaborative performance metrics, measure procurement performance using these metrics, align performance measurements and goals (CPO/CFO), and leverage opportunities and achieve leadership."},
	];
});
